#!/usr/bin/env bash
#Installing Nginx on Ubuntu
#Nginx is listening on port 80
#The GET request should return a page containing "Holberton School"

sudo apt-get update && upgrade
sudo apt-get install nginx -y

sed -i 's/listen\s*80/listen 0.0.0.0:80/' /etc/nginx/sites-available/dafault

service nginx start

sudo echo "Hello World" > /var/www/html/index.html
sudo echo "Hello World" > /etc/nginx/html/index.html
